//! Dynamic blocks and the column view built on them.

use helix_roam::dynamic::{block_at, blocks, columnview, refresh, refresh_all, rewrite};

const BLOCK: &str = "\
* Report
#+BEGIN: columnview :maxlevel 3 :columns \"ITEM TODO\"
stale contents
#+END:
after
";

#[test]
fn a_block_is_read_with_its_name_and_parameters() {
    let block = block_at(BLOCK, 1).unwrap();

    assert_eq!(block.name, "columnview");
    assert_eq!(block.number("maxlevel"), Some(3));
    assert_eq!(block.param("columns"), Some("ITEM TODO"));
    assert_eq!(block.start, 1);
    assert_eq!(block.end, 3);
}

#[test]
fn the_cursor_finds_the_block_from_anywhere_between_its_delimiters() {
    for line in 1..=3 {
        assert_eq!(block_at(BLOCK, line).unwrap().start, 1);
    }
    assert_eq!(block_at(BLOCK, 4), None);
}

#[test]
fn a_flag_without_a_value_is_still_a_parameter() {
    let text = "#+BEGIN: clocktable :hlines :scope file\n#+END:\n";
    let block = block_at(text, 0).unwrap();

    assert_eq!(block.param("hlines"), Some(""));
    assert_eq!(block.param("scope"), Some("file"));
    assert_eq!(block.param("maxlevel"), None);
}

#[test]
fn an_unclosed_block_is_a_typo_rather_than_a_block_to_the_end_of_the_file() {
    assert!(blocks("#+BEGIN: columnview\nsome text\n").is_empty());
}

#[test]
fn refreshing_replaces_the_contents_and_keeps_the_delimiters() {
    let out = refresh(BLOCK, 2, |_, block| {
        Some(vec![format!("generated by {}", block.name)])
    })
    .unwrap();

    assert_eq!(
        out,
        "\
* Report
#+BEGIN: columnview :maxlevel 3 :columns \"ITEM TODO\"
generated by columnview
#+END:
after
"
    );
}

#[test]
fn a_generator_that_does_not_know_the_name_leaves_the_buffer_alone() {
    assert_eq!(refresh(BLOCK, 2, |_, _| None), None);
}

#[test]
fn an_indented_block_keeps_its_indentation() {
    let text = "  #+BEGIN: thing\n  old\n  #+END:\n";
    let out = refresh(text, 0, |_, _| Some(vec!["new".to_string()])).unwrap();

    assert_eq!(out, "  #+BEGIN: thing\n  new\n  #+END:\n");
}

#[test]
fn every_block_is_refreshed_without_the_earlier_ones_moving_the_later() {
    let text = "#+BEGIN: a\nx\n#+END:\nmiddle\n#+BEGIN: b\ny\nz\n#+END:\n";
    let (out, done) = refresh_all(text, |_, block| Some(vec![block.name.to_uppercase()]));

    assert_eq!(done, 2);
    assert_eq!(
        out,
        "#+BEGIN: a\nA\n#+END:\nmiddle\n#+BEGIN: b\nB\n#+END:\n"
    );
}

#[test]
fn a_block_can_be_emptied() {
    let block = block_at(BLOCK, 1).unwrap();

    assert_eq!(
        rewrite(BLOCK, &block, &[]),
        "* Report\n#+BEGIN: columnview :maxlevel 3 :columns \"ITEM TODO\"\n#+END:\nafter\n"
    );
}

const NOTES: &str = "\
* Work
#+BEGIN: columnview :columns \"ITEM TODO EFFORT\"
#+END:
** TODO Write it
   :PROPERTIES:
   :EFFORT:   2h
   :END:
*** DONE Outline
** Review
* Elsewhere
** TODO Not in scope
";

#[test]
fn a_column_view_tabulates_the_subtree_it_sits_in() {
    let block = block_at(NOTES, 1).unwrap();
    let out = columnview(NOTES, &block);

    assert_eq!(
        out.join("\n"),
        "\
| Item      | Todo | Effort |
|-----------+------+--------|
| Work      |      |        |
|  Write it | TODO | 2h     |
|   Outline | DONE |        |
|  Review   |      |        |"
    );
}

#[test]
fn a_column_view_stops_at_the_subtree_it_belongs_to() {
    let block = block_at(NOTES, 1).unwrap();
    let out = columnview(NOTES, &block).join("\n");

    assert!(!out.contains("Not in scope"));
    assert!(!out.contains("Elsewhere"));
}

#[test]
fn maxlevel_cuts_the_view_off_at_a_depth() {
    let text = NOTES.replace(":columns", ":maxlevel 2 :columns");
    let block = block_at(&text, 1).unwrap();
    let out = columnview(&text, &block).join("\n");

    assert!(out.contains("Write it"));
    assert!(!out.contains("Outline"));
}

#[test]
fn the_default_columns_are_the_headline_and_its_keyword() {
    let text = "* Top\n#+BEGIN: columnview\n#+END:\n** TODO One\n";
    let block = block_at(text, 1).unwrap();

    assert_eq!(
        columnview(text, &block).join("\n"),
        "\
| Item | Todo |
|------+------|
| Top  |      |
|  One | TODO |"
    );
}

#[test]
fn a_view_of_nothing_is_empty_rather_than_a_header_alone() {
    let text = "#+BEGIN: columnview\n#+END:\n";
    let block = block_at(text, 0).unwrap();

    assert!(columnview(text, &block).is_empty());
}
